### PR TITLE
Aaa cu 9309dfngv test 2   legacy viktor stolbovoy CU-AAA-1236

### PR DESCRIPTION
**Pull request by ViktorStolbovoy**

### CODE REVIEW

**Comment by ViktorStolbovoy** [comment]
Task linked: [CU-9309dfngv Test 2 - legacy](https://local-fe.clickup.com/t/9309dfngv)

**Comment by ViktorStolbovoy** [comment]
Task linked: [9309dfngv_Test-2---legacy_Viktor-Stolbovoy ](https://local-fe.clickup.com/t/9999000003/9309dfngv_Test-2---legacy_Viktor-Stolbovoy))
Task linked: [AAA-1234 ](https://local-fe.clickup.com/t/9999000003/AAA-1234))

**Comment by ViktorStolbovoy** [comment]
aaaaa

**Comment by ViktorStolbovoy** [comment]
Task linked: [AAA-1236 ](https://local-fe.clickup.com/t/9999000003/AAA-1236)

**Comment by ViktorStolbovoyTest** [comment]
test

**Review by ViktorStolbovoyTest — APPROVED** [review]
Great!!!

**Pull request merged**
